sudo: required
services:
  - docker

before_install:
  - docker build -t qiwan/docker-react -f Dockerfile.dev .

script:
  - docker run qiwan/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "qi-docker-react"
  env: "QiDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-088589888966"
  bucket_path: "qi-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
